# Generated by Django 5.0.3 on 2024-03-24 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_landlordprofile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="landlordprofile",
            old_name="landlord_id",
            new_name="landlord",
        ),
    ]
