# Generated by Django 5.0.3 on 2024-03-24 16:08

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_rename_landlord_id_landlordprofile_landlord"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="landlordprofile",
            managers=[
                ("landlordProfile", django.db.models.manager.Manager()),
            ],
        ),
    ]
