# Generated by Django 5.0.3 on 2024-03-24 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_alter_landlordprofile_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="landlordprofile",
            managers=[],
        ),
    ]
