# Generated by Django 5.0.3 on 2024-03-25 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_alter_landlordprofile_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landlordprofile",
            name="landlord",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="landlordprofile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
