# Generated by Django 5.0.3 on 2024-03-25 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_alter_property_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="payment_date",
            field=models.DateTimeField(null=True),
        ),
    ]
